languageCode = "zh-TW"
languageName = "Traditional Chinese"
weight = 1
title = "嘰嘰乞乞"

[params]
  displayName = "中文"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  # secondaryLogo = "PATH"
  # description = "Avocado and Sloth's Blog"
  copyright = "© 2023 嘰嘰乞乞"

[author]
#  name = "Avocado"
#  image = "img/avocado_avatar.png"
#  headline = "The home of Sloth & Avocado, where we \"gigigatgat\"(chatter away) everything in our life"
#  bio = "重啟人生進行時"
#  links = [
#     { email = "mailto:tiffahahahu7@gmail.com" },
#     { mastodon = "https://mastodon.social/@siumai@unstable.icu" },
#     { github = "https://github.com/tiffahahahu7" },
#  ]

  